package io.suboptimal.buffjson;

import java.util.Map;

/**
 * Provides proto source comments for messages, fields, and enums. Generated by
 * the {@code buff-fastjson-protoc-plugin} and discovered at runtime via
 * {@link java.util.ServiceLoader}.
 *
 * <p>
 * Protoc strips {@code SourceCodeInfo} from descriptors embedded in generated
 * Java classes, making proto comments unavailable at runtime. This interface
 * bridges the gap: the protoc plugin receives full source info in the
 * {@code CodeGeneratorRequest} and generates a comment provider per
 * {@code .proto} file.
 *
 * <p>
 * Keys use protobuf full names matching
 * {@code Descriptor.getFullName()}/{@code FieldDescriptor.getFullName()}/{@code EnumDescriptor.getFullName()}.
 */
public interface GeneratedComments {

	/**
	 * Returns a map of protobuf full name to leading comment text. Keys follow
	 * protobuf naming: {@code "my.package.MyMessage"},
	 * {@code "my.package.MyMessage.my_field"}, {@code "my.package.MyEnum"}.
	 */
	Map<String, String> getComments();
}
