package io.suboptimal.buffjson;

import com.alibaba.fastjson2.JSONWriter;
import com.google.protobuf.Message;

/**
 * Generated per-message-type encoder that uses typed accessors instead of
 * reflection-style {@code getField()}.
 *
 * <p>
 * Implementations are generated by the {@code buff-fastjson-protoc-plugin} and
 * discovered at runtime via {@link java.util.ServiceLoader}. When a generated
 * encoder is available for a message type, it is used automatically — no code
 * changes required.
 *
 * @param <T>
 *            the concrete protobuf message type
 */
public interface GeneratedEncoder<T extends Message> {

	/** The fully-qualified protobuf type name (e.g., "my.package.MyMessage"). */
	String descriptorFullName();

	/**
	 * Writes all non-default fields of the message as JSON object content (without
	 * surrounding braces). The caller is responsible for
	 * {@code startObject}/{@code endObject}.
	 */
	void writeFields(JSONWriter jsonWriter, T message);
}
